## npm packages
[packages.cli]
versioned_files = [
  "packages/@simora-uk/ripari/package.json",
  "packages/@simora-uk/cli-darwin-arm64/package.json",
  "packages/@simora-uk/cli-darwin-x64/package.json",
  "packages/@simora-uk/cli-linux-arm64/package.json",
  "packages/@simora-uk/cli-linux-x64/package.json",
  "packages/@simora-uk/cli-win32-arm64/package.json",
  "packages/@simora-uk/cli-win32-x64/package.json"
]

[packages.ripari_cli]
versioned_files = ["crates/ripari_cli/Cargo.toml"]

[packages.simora_configuration]
versioned_files = ["crates/simora_configuration/Cargo.toml"]

[packages.simora_formatter]
versioned_files = ["crates/simora_formatter/Cargo.toml"]

[packages.simora_glob]
versioned_files = ["crates/simora_glob/Cargo.toml"]

# Workflow for bumping versions
[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"
ignore_conventional_commits = true
# Ensure versions are always bumped, even if no changes are detected
allow_empty = true

[[workflows.steps]]
type = "Command"
command = "cargo update -w"  # Update Cargo.lock to reflect new versions

[[workflows.steps]]
type = "Command"
command = "git commit -am 'chore: bump versions for pre-release'"

[[workflows.steps]]
type = "Command"
command = "git push --set-upstream origin bump-version/pre-release"

[[workflows.steps]]
base = "main"
type = "CreatePullRequest"

[workflows.steps.title]
template = "chore: bump versions for pre-release"

[workflows.steps.body]
template = "This PR contains version updates for the upcoming pre-release stage."

[github]
owner = "simora-uk"
repo = "ripari"

[prepare-release]
bump = "minor"  # Options: "patch", "minor", "major"

[versioning]
starting-version = "1.0.0"  # Optional: Define a starting version if tags are missing
