[package]
name = "simora_prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
walkdir = "2"
serde_json = "1.0"
simora_glob = { path = "../simora_glob" }
simora_formatter = { path = "../simora_formatter" }
simora_configuration = { path = "../simora_configuration" }
