[alias]
codegen               = "run -p xtask_codegen --"
codegen-bindings      = "run -p xtask_codegen --features schema -- bindings"
codegen-configuration = "run -p xtask_codegen --features configuration -- configuration"
simora-prompt-cli     = "run -p simora-prompt_cli --release --"
simora-prompt-cli-dev = "run -p simora-prompt_cli --"
# updates a newly created crate
codegen-license = "run -p xtask_codegen --features license -- license"
codegen-migrate = "run -p xtask_codegen --features configuration -- migrate-eslint"
codegen-schema = "run -p xtask_codegen --features schema -- schema"
contributors = "run -p xtask_contributors --"
coverage = "run -p xtask_coverage --profile=release-with-debug --"
documentation = """
    doc \
    -p simora-prompt_*formatter \
    -p simora-prompt_control_flow \
    -p simora-prompt_analyze \
    -p simora-prompt_*analyze \
    -p simora-prompt_*_syntax \
    -p simora-prompt_*_factory \
    -p simora-prompt_diagnostics \
    -p simora-prompt_service \
    -p simora-prompt_cli \
    -p simora-prompt_console \
    -p simora-prompt_*parser \
    -p simora-prompt_text_edit \
    -p simora-prompt_text_size \
    -p simora-prompt_js_semantic \
    -p simora-prompt_markup \
    -p simora-prompt_rowan
    -p simora-prompt_string_case \
    -p simora-prompt_configuration \
    --no-deps
"""
format = "fmt --all --verbose"
lint = "clippy --workspace --all-targets -- --deny warnings"
new-crate = "run -p xtask_codegen -- new-crate"

[profile.release]
lto = true
