[alias]
codegen               = "run -p xtask_codegen --"
codegen-bindings      = "run -p xtask_codegen --features schema -- bindings"
codegen-configuration = "run -p xtask_codegen --features configuration -- configuration"
ripari-cli     = "run -p ripari_cli --release --"
ripari-cli-dev = "run -p ripari_cli --"
# updates a newly created crate
codegen-license = "run -p xtask_codegen --features license -- license"
codegen-migrate = "run -p xtask_codegen --features configuration -- migrate-eslint"
codegen-schema = "run -p xtask_codegen --features schema -- schema"
contributors = "run -p xtask_contributors --"
coverage = "run -p xtask_coverage --profile=release-with-debug --"
documentation = """
    doc \
    -p ripari_*formatter \
    -p ripari_control_flow \
    -p ripari_analyze \
    -p ripari_*analyze \
    -p ripari_*_syntax \
    -p ripari_*_factory \
    -p ripari_diagnostics \
    -p ripari_service \
    -p ripari_cli \
    -p ripari_console \
    -p ripari_*parser \
    -p ripari_text_edit \
    -p ripari_text_size \
    -p ripari_js_semantic \
    -p ripari_markup \
    -p ripari_rowan
    -p ripari_string_case \
    -p ripari_configuration \
    --no-deps
"""
format = "fmt --all --verbose"
lint = "clippy --workspace --all-targets -- --deny warnings"
new-crate = "run -p xtask_codegen -- new-crate"

[profile.release]
lto = true
