[package]
name = "simora_formatter"
version = "0.1.0"
edition = "2021"
description = "Formatter traits and implementations for Simora Prompt"

[dependencies]
# Core dependencies
simora_prompt = { path = "../simora_prompt" }

# For formatting functionality
regex = "1.10.2"
